### ISSUE TITLE
Latest Version

### ISSUE THREAD

**Issue by yograjyog** [SUSradfys/Checklista#3]
Dear Mr Jonas

Recently I came across your CHECKLISTA repository on GITHUB and really interested in trying it, but our Eclipse version is 15.6. By chance, if you have CHECKLISTA for a newer version  please let me know. Your help is much appreciated.

**Comment by Megatram** [comment]
Hi. 
Currently this checklist is not available from github in v 15.6. However you should be able to rebuild it to 15.6 using the dependencies from varian (types and model.dll). 

Jonas
